In [ ]:
clear all
addpath('./biblioteca')
graphics_toolkit ("gnuplot");

In [16]:
b = [1, 2];

B = b' * b

%%[L, U, P] = LU_PP(B)

[S, V, D] = svd(B)

L = choleski(B)

eig(B)


B =

   1   2
   2   4

S =

  -0.4472  -0.8944
  -0.8944   0.4472

V =

Diagonal Matrix

   5.0000e+00            0
            0   1.9860e-16

D =

  -0.4472  -0.8944
  -0.8944   0.4472

error: No hay factorizaci�n
error: called from
    choleski at line 21 column 7
ans =

   0
   5



# Hoja 1:

## Ejercicio 1: 
(PG. 50)

In [39]:
clear all

A = [1:3; 4:6; 7:9; 10:12; 13:15]

B = NonsingularMat(3)
C = NonsingularMat(5)

CA = C*A
AB = A*B

display("A:\n")
rA = rank(A)
printf("Rango: %s\n", num2str(rA))

display("CA:\n")
rCA = rank(CA)
printf("Rango: %s\n", num2str(rCA))

display("\nAB:")
rAB = rank(AB);
printf("Rango: %s", num2str(rAB))


A =

    1    2    3
    4    5    6
    7    8    9
   10   11   12
   13   14   15

B =

   3.398714   0.832874   0.916476
   0.801384   2.626008   0.993916
   0.053360   0.194175   2.696868

C =

   4.506286   0.909935   0.067756   0.054787   0.470293
   0.985722   3.937149   0.630257   0.778924   0.680998
   0.284755   0.136614   4.107034   0.979116   0.625439
   0.642493   0.707756   0.478649   3.787438   0.894218
   0.437158   0.147477   0.194976   0.282343   3.821008

CA =

   15.282   21.291   27.300
   37.788   44.801   51.814
   47.502   53.635   59.768
   56.323   62.834   69.344
   54.888   59.771   64.654

AB =

    5.1616    6.6674   10.9949
   17.9219   17.6266   24.8167
   30.6823   28.5858   38.6385
   43.4427   39.5449   52.4603
   56.2030   50.5041   66.2820

A:

rA = 2
Rango: 2
CA:

rCA = 2
Rango: 2

AB:
Rango: 2

Los rangos no cambian pues al ser B y C no singulares su producto por otra matriz no cambia el rango de esta última.

## Ejercio 5:

In [44]:
clear all

A = [1:3; 4:6; 7:9; 10:12]
B = [-1 2 3; 4:6; 7:9; 10:12; 13:15]

AA = A'*A
BB = B'*B

detAA = det(AA)
detBB = det(BB)

rAA = rank(AA)
rBB = rank(BB)

A =

    1    2    3
    4    5    6
    7    8    9
   10   11   12

B =

   -1    2    3
    4    5    6
    7    8    9
   10   11   12
   13   14   15

AA =

   166   188   210
   188   214   240
   210   240   270

BB =

   335   366   399
   366   410   450
   399   450   495

detAA = 0
detBB = 720.00
rAA = 2
rBB = 3


## Ejercicio 6:

Comparamos la velocidad al definir una matriz de diferentes maneras.

In [47]:
clear all
n=400;

% Va creando los espacios de memoria según necesita.
tic;
for j=1:n
    for i=1:n
        a(i,j)=cos(i)*sin(j);
    end
end
t1=toc
clear a;

% Crea primero el espacio de memoria y luego reescribe.
tic
a=zeros(n,n);
for j=1:n
    for i=1:n
        a(i,j)=cos(i)*sin(j);
    end
end
t2=toc
clear a;

% Igual que el anterior pero recorre fila a fila en luegar de columna en columna.
tic;
a=zeros(n,n);
for i=1:n
    for j=1:n
        a(i,j)=cos(i)*sin(j);
    end
end
t3=toc
clear a;

% Aloca primero la memoria y luego la reescribe con el cálculo matricial directamente.
tic
a=zeros(n,n);
a=cos(1:n)'*sin(1:n);
t4=toc




t1 = 2.8977
t2 = 2.8294
t3 = 2.7591
t4 = 0.3337


## Ejercicio 7:

In [58]:
clear all
n = 2:1:5;

for i=1:length(n)
    printf("n = %u\n", n(i))
    A = rand(n(i), n(i));
    a = eig(A)
    at = eig(A')
endfor

n = 2
a =

   0.2773
   0.8618

at =

   0.2773
   0.8618

n = 3
a =

   1.4449
  -0.6067
   0.2492

at =

   1.4449
  -0.6067
   0.2492

n = 4
a =

   1.875627
   0.356774
   0.245363
   0.011725

at =

   1.875627
   0.356774
   0.245363
   0.011725

n = 5
a =

   2.3057 +      0i
  -0.0467 + 0.2795i
  -0.0467 - 0.2795i
   0.2985 + 0.2675i
   0.2985 - 0.2675i

at =

   2.3057 +      0i
   0.2985 + 0.2675i
   0.2985 - 0.2675i
  -0.0467 + 0.2795i
  -0.0467 - 0.2795i



In [68]:
clear all
m = [2, 6];
n = [4, 5];

for i=1:length(m)
    printf("i = %u\n", i)
    A = rand(n(i),m(i));
    deter = det(A'*A)
    aat = eig(A*A')
    ata = eig(A'*A)
    clear deter
endfor

i = 1
deter = 0.014584
aat =

  -1.9935e-16
   9.7433e-17
   6.5394e-03
   2.2302e+00

ata =

   6.5394e-03
   2.2302e+00

i = 2
deter = -6.5077e-19
aat =

   3.1495e-02
   1.1243e-01
   1.9541e-01
   8.9414e-01
   1.3555e+01

ata =

   9.5058e-17
   3.1495e-02
   1.1243e-01
   1.9541e-01
   8.9414e-01
   1.3555e+01



In [71]:
clear all

A = [1,1,2;1,0,-2;-1,2,3]
[Q,R] = Householdergramschmidt(A)

B = [1, 1, 1;
    1, 1, 1;
    1, 1, 1]

eig(B)

A =

   1   1   2
   1   0  -2
  -1   2   3

Q =

   0.5774   0.6172   0.5345
   0.5774   0.1543  -0.8018
  -0.5774   0.7715  -0.2673

R =

   1.7321  -0.5774  -1.7321
        0   2.1602   3.2404
        0        0   1.8708

B =

   1   1   1
   1   1   1
   1   1   1

ans =

  -5.6242e-16
   7.3053e-18
   3.0000e+00

